# Generated by Django 5.0.7 on 2024-08-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unique_id',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
