# Generated by Django 5.0.7 on 2024-08-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_message_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='unique_id',
        ),
    ]
