# Generated by Django 5.0.7 on 2024-08-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_message_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unique_id',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
